81460d8b971730c8f27ccbff374e2e79_1:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 1
81460d8b971730c8f27ccbff374e2e79_5:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 5
81460d8b971730c8f27ccbff374e2e79_6:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 6
81460d8b971730c8f27ccbff374e2e79_7:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 7
