81460d8b971730c8f27ccbff374e2e79_1:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 1
81460d8b971730c8f27ccbff374e2e79_2:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 2
81460d8b971730c8f27ccbff374e2e79_3:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 3
81460d8b971730c8f27ccbff374e2e79_4:
  con_name: xorq
  kwargs_tuple:
    config: null
  idx: 4
